const CATS={op:{n:"Operations",n2:"操作词",d:"动词、介词、代词、连词等"},gn:{n:"General Things",n2:"一般事物",d:"抽象名词"},pt:{n:"Picturable Things",n2:"可画名词",d:"具体可视的事物"},qg:{n:"Qualities",n2:"一般性质",d:"形容词"},qo:{n:"Opposites",n2:"对立性质",d:"反义形容词"}};
const SUBS={verb:"动词",prep:"介词",conj:"连词",pron:"代词",det:"限定词",adv:"副词",abstract:"抽象",nature:"自然",material:"材料",food:"食物",people:"人物",time:"时间",adj:"形容词",body:"身体",animal:"动物",clothing:"服饰",building:"建筑",tool:"工具",plant:"植物",vehicle:"交通"};
const D=`come|/kʌm/|来，到来|op|verb
get|/ɡet/|得到，变得|op|verb
give|/ɡɪv/|给，给予|op|verb
go|/ɡoʊ/|去，前往|op|verb
keep|/kiːp/|保持，保留|op|verb
let|/let/|让，允许|op|verb
make|/meɪk/|制作，使|op|verb
put|/pʊt/|放，放置|op|verb
seem|/siːm/|似乎，好像|op|verb
take|/teɪk/|拿，带走|op|verb
be|/biː/|是，存在|op|verb
do|/duː/|做，执行|op|verb
have|/hæv/|有，拥有|op|verb
say|/seɪ/|说，讲|op|verb
see|/siː/|看见，明白|op|verb
send|/send/|发送，寄|op|verb
may|/meɪ/|可能，可以|op|verb
will|/wɪl/|将，愿意|op|verb
about|/əˈbaʊt/|关于，大约|op|prep
across|/əˈkrɒs/|穿过，横过|op|prep
after|/ˈæftər/|在…之后|op|prep
against|/əˈɡenst/|反对，靠着|op|prep
among|/əˈmʌŋ/|在…之中|op|prep
at|/æt/|在，于|op|prep
before|/bɪˈfɔːr/|在…之前|op|prep
between|/bɪˈtwiːn/|在…之间|op|prep
by|/baɪ/|由，被，通过|op|prep
down|/daʊn/|向下，沿|op|prep
from|/frɒm/|从，来自|op|prep
in|/ɪn/|在…里|op|prep
off|/ɒf/|离开，脱离|op|prep
on|/ɒn/|在…上|op|prep
over|/ˈoʊvər/|在…上方，超过|op|prep
through|/θruː/|通过，穿过|op|prep
to|/tuː/|到，向|op|prep
under|/ˈʌndər/|在…下面|op|prep
up|/ʌp/|向上，起来|op|prep
with|/wɪð/|和，用|op|prep
as|/æz/|作为，如同|op|conj
for|/fɔːr/|为了，因为|op|prep
of|/ɒv/|…的，属于|op|prep
till|/tɪl/|直到|op|conj
than|/ðæn/|比|op|conj
a|/ə/|一个|op|det
the|/ðə/|这个，那个|op|det
all|/ɔːl/|所有，全部|op|det
any|/ˈeni/|任何，一些|op|det
every|/ˈevri/|每个，每一|op|det
no|/noʊ/|不，没有|op|det
other|/ˈʌðər/|其他的，另外的|op|det
some|/sʌm/|一些，某些|op|det
such|/sʌtʃ/|如此的，这样的|op|det
that|/ðæt/|那个，那|op|det
this|/ðɪs/|这个，这|op|det
I|/aɪ/|我|op|pron
he|/hiː/|他|op|pron
you|/juː/|你，你们|op|pron
who|/huː/|谁|op|pron
and|/ænd/|和，与|op|conj
because|/bɪˈkɒz/|因为|op|conj
but|/bʌt/|但是，然而|op|conj
or|/ɔːr/|或者，还是|op|conj
if|/ɪf/|如果，假如|op|conj
though|/ðoʊ/|虽然，尽管|op|conj
while|/waɪl/|当…时，虽然|op|conj
how|/haʊ/|如何，怎样|op|adv
when|/wen/|何时，当…时|op|adv
where|/wer/|哪里，在哪里|op|adv
why|/waɪ/|为什么|op|adv
again|/əˈɡen/|再次，又|op|adv
ever|/ˈevər/|曾经，究竟|op|adv
far|/fɑːr/|远，遥远|op|adv
forward|/ˈfɔːrwərd/|向前，前进|op|adv
here|/hɪr/|这里，在这里|op|adv
near|/nɪr/|附近，靠近|op|adv
now|/naʊ/|现在，此刻|op|adv
out|/aʊt/|出，在外面|op|adv
still|/stɪl/|仍然，静止|op|adv
then|/ðen/|然后，那时|op|adv
there|/ðer/|那里，在那里|op|adv
together|/təˈɡeðər/|一起，共同|op|adv
well|/wel/|好，很好地|op|adv
almost|/ˈɔːlmoʊst/|几乎，差不多|op|adv
enough|/ɪˈnʌf/|足够，充分|op|adv
even|/ˈiːvən/|甚至，即使|op|adv
little|/ˈlɪtl/|小的，少的|op|adv
much|/mʌtʃ/|多，很多|op|adv
not|/nɒt/|不，没有|op|adv
only|/ˈoʊnli/|只有，仅仅|op|adv
quite|/kwaɪt/|相当，十分|op|adv
so|/soʊ/|如此，所以|op|adv
very|/ˈveri/|非常，很|op|adv
tomorrow|/təˈmɒroʊ/|明天|op|adv
yesterday|/ˈjestərdeɪ/|昨天|op|adv
north|/nɔːrθ/|北，北方|op|adv
south|/saʊθ/|南，南方|op|adv
east|/iːst/|东，东方|op|adv
west|/west/|西，西方|op|adv
please|/pliːz/|请|op|adv
yes|/jes/|是，好的|op|adv
account|/əˈkaʊnt/|账户，叙述|gn|abstract
act|/ækt/|行为，行动|gn|abstract
addition|/əˈdɪʃn/|增加，加法|gn|abstract
adjustment|/əˈdʒʌstmənt/|调整，调节|gn|abstract
advertisement|/ˌædvərˈtaɪzmənt/|广告|gn|abstract
agreement|/əˈɡriːmənt/|协议，同意|gn|abstract
air|/er/|空气，天空|gn|nature
amount|/əˈmaʊnt/|数量，总额|gn|abstract
amusement|/əˈmjuːzmənt/|娱乐，消遣|gn|abstract
animal|/ˈænɪml/|动物|gn|nature
answer|/ˈænsər/|回答，答案|gn|abstract
apparatus|/ˌæpəˈreɪtəs/|器械，装置|gn|abstract
approval|/əˈpruːvl/|批准，赞成|gn|abstract
argument|/ˈɑːrɡjumənt/|争论，论点|gn|abstract
art|/ɑːrt/|艺术，技艺|gn|abstract
attack|/əˈtæk/|攻击，进攻|gn|abstract
attempt|/əˈtempt/|尝试，企图|gn|abstract
attention|/əˈtenʃn/|注意力，关注|gn|abstract
attraction|/əˈtrækʃn/|吸引力，吸引|gn|abstract
authority|/ɔːˈθɒrəti/|权威，当局|gn|abstract
back|/bæk/|背部，后面|gn|abstract
balance|/ˈbæləns/|平衡，天平|gn|abstract
base|/beɪs/|基础，基地|gn|abstract
behaviour|/bɪˈheɪvjər/|行为，举止|gn|abstract
belief|/bɪˈliːf/|信念，信仰|gn|abstract
birth|/bɜːrθ/|出生，诞生|gn|abstract
bit|/bɪt/|一点，小块|gn|abstract
bite|/baɪt/|咬，一口|gn|abstract
blood|/blʌd/|血液|gn|nature
blow|/bloʊ/|吹，打击|gn|abstract
body|/ˈbɒdi/|身体，主体|gn|abstract
brass|/bræs/|黄铜|gn|material
bread|/bred/|面包|gn|food
breath|/breθ/|呼吸，气息|gn|abstract
brother|/ˈbrʌðər/|兄弟|gn|people
building|/ˈbɪldɪŋ/|建筑物|gn|abstract
burn|/bɜːrn/|燃烧，烧伤|gn|abstract
burst|/bɜːrst/|爆发，破裂|gn|abstract
business|/ˈbɪznəs/|商业，事务|gn|abstract
butter|/ˈbʌtər/|黄油|gn|food
canvas|/ˈkænvəs/|帆布，画布|gn|material
care|/ker/|关心，照顾|gn|abstract
cause|/kɔːz/|原因，事业|gn|abstract
chalk|/tʃɔːk/|粉笔|gn|material
chance|/tʃæns/|机会，偶然|gn|abstract
change|/tʃeɪndʒ/|变化，改变|gn|abstract
cloth|/klɒθ/|布，织物|gn|material
coal|/koʊl/|煤|gn|material
colour|/ˈkʌlər/|颜色，色彩|gn|abstract
comfort|/ˈkʌmfərt/|舒适，安慰|gn|abstract
committee|/kəˈmɪti/|委员会|gn|abstract
company|/ˈkʌmpəni/|公司，陪伴|gn|abstract
comparison|/kəmˈpærɪsn/|比较，对比|gn|abstract
competition|/ˌkɒmpəˈtɪʃn/|竞争，比赛|gn|abstract
condition|/kənˈdɪʃn/|条件，状况|gn|abstract
connection|/kəˈnekʃn/|连接，关系|gn|abstract
control|/kənˈtroʊl/|控制，管理|gn|abstract
cook|/kʊk/|厨师，烹饪|gn|abstract
copper|/ˈkɒpər/|铜|gn|material
copy|/ˈkɒpi/|副本，复制|gn|abstract
cork|/kɔːrk/|软木，瓶塞|gn|material
cotton|/ˈkɒtn/|棉花|gn|material
cough|/kɒf/|咳嗽|gn|abstract
country|/ˈkʌntri/|国家，乡村|gn|abstract
cover|/ˈkʌvər/|覆盖，封面|gn|abstract
crack|/kræk/|裂缝，破裂|gn|abstract
credit|/ˈkredɪt/|信用，信贷|gn|abstract
crime|/kraɪm/|犯罪，罪行|gn|abstract
crush|/krʌʃ/|压碎，镇压|gn|abstract
cry|/kraɪ/|哭，叫喊|gn|abstract
current|/ˈkɜːrənt/|电流，当前|gn|abstract
curve|/kɜːrv/|曲线，弯曲|gn|abstract
damage|/ˈdæmɪdʒ/|损害，伤害|gn|abstract
danger|/ˈdeɪndʒər/|危险|gn|abstract
daughter|/ˈdɔːtər/|女儿|gn|people
day|/deɪ/|天，白天|gn|time
death|/deθ/|死亡|gn|abstract
debt|/det/|债务，欠款|gn|abstract
decision|/dɪˈsɪʒn/|决定，决心|gn|abstract
degree|/dɪˈɡriː/|程度，学位|gn|abstract
design|/dɪˈzaɪn/|设计，图案|gn|abstract
desire|/dɪˈzaɪər/|欲望，渴望|gn|abstract
destruction|/dɪˈstrʌkʃn/|破坏，毁灭|gn|abstract
detail|/ˈdiːteɪl/|细节，详情|gn|abstract
development|/dɪˈveləpmənt/|发展，开发|gn|abstract
digestion|/daɪˈdʒestʃən/|消化|gn|abstract
direction|/dɪˈrekʃn/|方向，指导|gn|abstract
discovery|/dɪˈskʌvəri/|发现|gn|abstract
discussion|/dɪˈskʌʃn/|讨论，议论|gn|abstract
disease|/dɪˈziːz/|疾病|gn|abstract
disgust|/dɪsˈɡʌst/|厌恶，反感|gn|abstract
distance|/ˈdɪstəns/|距离|gn|abstract
distribution|/ˌdɪstrɪˈbjuːʃn/|分配，分布|gn|abstract
division|/dɪˈvɪʒn/|分割，部门|gn|abstract
doubt|/daʊt/|怀疑，疑问|gn|abstract
drink|/drɪŋk/|饮料，喝|gn|food
driving|/ˈdraɪvɪŋ/|驾驶，驱动|gn|abstract
dust|/dʌst/|灰尘，尘土|gn|nature
earth|/ɜːrθ/|地球，泥土|gn|nature
edge|/edʒ/|边缘，刀刃|gn|abstract
education|/ˌedʒuˈkeɪʃn/|教育|gn|abstract
effect|/ɪˈfekt/|效果，影响|gn|abstract
end|/end/|结束，末端|gn|abstract
error|/ˈerər/|错误，误差|gn|abstract
event|/ɪˈvent/|事件，大事|gn|abstract
example|/ɪɡˈzæmpl/|例子，榜样|gn|abstract
exchange|/ɪksˈtʃeɪndʒ/|交换，兑换|gn|abstract
existence|/ɪɡˈzɪstəns/|存在，生存|gn|abstract
expansion|/ɪkˈspænʃn/|扩张，膨胀|gn|abstract
experience|/ɪkˈspɪriəns/|经验，经历|gn|abstract
expert|/ˈekspɜːrt/|专家|gn|people
fact|/fækt/|事实，真相|gn|abstract
fall|/fɔːl/|秋天，落下|gn|abstract
family|/ˈfæməli/|家庭，家族|gn|people
father|/ˈfɑːðər/|父亲|gn|people
fear|/fɪr/|恐惧，害怕|gn|abstract
feeling|/ˈfiːlɪŋ/|感觉，情感|gn|abstract
fiction|/ˈfɪkʃn/|小说，虚构|gn|abstract
field|/fiːld/|田野，领域|gn|nature
fight|/faɪt/|战斗，打架|gn|abstract
fire|/ˈfaɪər/|火，火灾|gn|nature
flame|/fleɪm/|火焰|gn|nature
flight|/flaɪt/|飞行，航班|gn|abstract
flower|/ˈflaʊər/|花|gn|nature
fold|/foʊld/|折叠，褶|gn|abstract
food|/fuːd/|食物|gn|food
force|/fɔːrs/|力量，武力|gn|abstract
form|/fɔːrm/|形式，表格|gn|abstract
friend|/frend/|朋友|gn|people
front|/frʌnt/|前面，前线|gn|abstract
fruit|/fruːt/|水果，果实|gn|food
glass|/ɡlæs/|玻璃，杯子|gn|material
gold|/ɡoʊld/|黄金|gn|material
government|/ˈɡʌvərnmənt/|政府|gn|abstract
grain|/ɡreɪn/|谷物，颗粒|gn|nature
grass|/ɡræs/|草，草地|gn|nature
grip|/ɡrɪp/|握力，控制|gn|abstract
group|/ɡruːp/|群，组|gn|abstract
growth|/ɡroʊθ/|生长，增长|gn|abstract
guide|/ɡaɪd/|向导，指南|gn|abstract
harbour|/ˈhɑːrbər/|港口，避风港|gn|abstract
harmony|/ˈhɑːrməni/|和谐，协调|gn|abstract
hate|/heɪt/|仇恨，厌恶|gn|abstract
hearing|/ˈhɪrɪŋ/|听力，审讯|gn|abstract
heat|/hiːt/|热，热量|gn|nature
help|/help/|帮助|gn|abstract
history|/ˈhɪstəri/|历史|gn|abstract
hole|/hoʊl/|洞，孔|gn|abstract
hope|/hoʊp/|希望|gn|abstract
hour|/ˈaʊər/|小时，时间|gn|time
humour|/ˈhjuːmər/|幽默，心情|gn|abstract
ice|/aɪs/|冰|gn|nature
idea|/aɪˈdiːə/|想法，主意|gn|abstract
impulse|/ˈɪmpʌls/|冲动，脉冲|gn|abstract
increase|/ˈɪnkriːs/|增加，增长|gn|abstract
industry|/ˈɪndəstri/|工业，产业|gn|abstract
ink|/ɪŋk/|墨水|gn|material
insect|/ˈɪnsekt/|昆虫|gn|nature
instrument|/ˈɪnstrəmənt/|乐器，工具|gn|abstract
insurance|/ɪnˈʃʊrəns/|保险|gn|abstract
interest|/ˈɪntrəst/|兴趣，利息|gn|abstract
invention|/ɪnˈvenʃn/|发明|gn|abstract
iron|/ˈaɪərn/|铁|gn|material
jelly|/ˈdʒeli/|果冻，胶状物|gn|food
join|/dʒɔɪn/|连接，加入|gn|abstract
journey|/ˈdʒɜːrni/|旅程，旅行|gn|abstract
judge|/dʒʌdʒ/|法官，裁判|gn|people
jump|/dʒʌmp/|跳跃|gn|abstract
kick|/kɪk/|踢|gn|abstract
kiss|/kɪs/|吻|gn|abstract
knowledge|/ˈnɒlɪdʒ/|知识，学问|gn|abstract
land|/lænd/|土地，陆地|gn|nature
language|/ˈlæŋɡwɪdʒ/|语言|gn|abstract
laugh|/læf/|笑，笑声|gn|abstract
law|/lɔː/|法律，规律|gn|abstract
lead|/liːd/|领导，铅|gn|abstract
learning|/ˈlɜːrnɪŋ/|学习，知识|gn|abstract
leather|/ˈleðər/|皮革|gn|material
letter|/ˈletər/|信，字母|gn|abstract
level|/ˈlevl/|水平，等级|gn|abstract
lift|/lɪft/|举起，电梯|gn|abstract
light|/laɪt/|光，灯|gn|nature
limit|/ˈlɪmɪt/|限制，界限|gn|abstract
linen|/ˈlɪnɪn/|亚麻布|gn|material
liquid|/ˈlɪkwɪd/|液体|gn|abstract
list|/lɪst/|列表，名单|gn|abstract
look|/lʊk/|看，外观|gn|abstract
loss|/lɒs/|损失，丧失|gn|abstract
love|/lʌv/|爱，热爱|gn|abstract
machine|/məˈʃiːn/|机器|gn|abstract
man|/mæn/|男人，人类|gn|people
manager|/ˈmænɪdʒər/|经理，管理者|gn|people
mark|/mɑːrk/|标记，分数|gn|abstract
market|/ˈmɑːrkɪt/|市场|gn|abstract
mass|/mæs/|质量，群众|gn|abstract
meal|/miːl/|一餐，饭|gn|food
measure|/ˈmeʒər/|测量，措施|gn|abstract
meat|/miːt/|肉|gn|food
meeting|/ˈmiːtɪŋ/|会议，会面|gn|abstract
memory|/ˈmeməri/|记忆，内存|gn|abstract
metal|/ˈmetl/|金属|gn|material
middle|/ˈmɪdl/|中间，中部|gn|abstract
milk|/mɪlk/|牛奶|gn|food
mind|/maɪnd/|头脑，心思|gn|abstract
mine|/maɪn/|矿，我的|gn|abstract
minute|/ˈmɪnɪt/|分钟|gn|time
mist|/mɪst/|薄雾|gn|nature
money|/ˈmʌni/|钱，货币|gn|abstract
month|/mʌnθ/|月，月份|gn|time
morning|/ˈmɔːrnɪŋ/|早晨|gn|time
mother|/ˈmʌðər/|母亲|gn|people
motion|/ˈmoʊʃn/|运动，动议|gn|abstract
mountain|/ˈmaʊntən/|山|gn|nature
move|/muːv/|移动，搬家|gn|abstract
music|/ˈmjuːzɪk/|音乐|gn|abstract
name|/neɪm/|名字，名称|gn|abstract
nation|/ˈneɪʃn/|国家，民族|gn|abstract
need|/niːd/|需要，需求|gn|abstract
news|/njuːz/|新闻，消息|gn|abstract
night|/naɪt/|夜晚|gn|time
noise|/nɔɪz/|噪音，声响|gn|abstract
note|/noʊt/|笔记，便条|gn|abstract
number|/ˈnʌmbər/|数字，号码|gn|abstract
observation|/ˌɒbzərˈveɪʃn/|观察|gn|abstract
offer|/ˈɒfər/|提议，提供|gn|abstract
oil|/ɔɪl/|油，石油|gn|material
operation|/ˌɒpəˈreɪʃn/|操作，手术|gn|abstract
opinion|/əˈpɪnjən/|意见，看法|gn|abstract
order|/ˈɔːrdər/|秩序，命令|gn|abstract
organization|/ˌɔːrɡənaɪˈzeɪʃn/|组织，机构|gn|abstract
ornament|/ˈɔːrnəmənt/|装饰，装饰品|gn|abstract
owner|/ˈoʊnər/|所有者，物主|gn|people
page|/peɪdʒ/|页|gn|abstract
pain|/peɪn/|疼痛，痛苦|gn|abstract
paint|/peɪnt/|油漆，绘画|gn|abstract
paper|/ˈpeɪpər/|纸，论文|gn|material
part|/pɑːrt/|部分，角色|gn|abstract
paste|/peɪst/|糊，浆糊|gn|abstract
payment|/ˈpeɪmənt/|付款，支付|gn|abstract
peace|/piːs/|和平，安宁|gn|abstract
person|/ˈpɜːrsn/|人，人物|gn|people
place|/pleɪs/|地方，位置|gn|abstract
plant|/plænt/|植物，工厂|gn|nature
play|/pleɪ/|游戏，戏剧|gn|abstract
pleasure|/ˈpleʒər/|快乐，荣幸|gn|abstract
point|/pɔɪnt/|点，要点|gn|abstract
poison|/ˈpɔɪzn/|毒药，毒物|gn|abstract
polish|/ˈpɒlɪʃ/|抛光，润色|gn|abstract
porter|/ˈpɔːrtər/|搬运工|gn|people
position|/pəˈzɪʃn/|位置，职位|gn|abstract
powder|/ˈpaʊdər/|粉末，火药|gn|abstract
power|/ˈpaʊər/|力量，权力|gn|abstract
price|/praɪs/|价格，代价|gn|abstract
print|/prɪnt/|印刷，打印|gn|abstract
process|/ˈprɒses/|过程，工序|gn|abstract
produce|/ˈprɒdjuːs/|产品，农产品|gn|abstract
profit|/ˈprɒfɪt/|利润，利益|gn|abstract
property|/ˈprɒpərti/|财产，属性|gn|abstract
prose|/proʊz/|散文|gn|abstract
protest|/ˈproʊtest/|抗议，反对|gn|abstract
pull|/pʊl/|拉，拖|gn|abstract
punishment|/ˈpʌnɪʃmənt/|惩罚，处罚|gn|abstract
purpose|/ˈpɜːrpəs/|目的，意图|gn|abstract
push|/pʊʃ/|推，推动|gn|abstract
quality|/ˈkwɒləti/|质量，品质|gn|abstract
question|/ˈkwestʃən/|问题，疑问|gn|abstract
rain|/reɪn/|雨|gn|nature
range|/reɪndʒ/|范围，山脉|gn|abstract
rate|/reɪt/|比率，速度|gn|abstract
ray|/reɪ/|光线，射线|gn|nature
reaction|/riˈækʃn/|反应，回应|gn|abstract
reading|/ˈriːdɪŋ/|阅读，读物|gn|abstract
reason|/ˈriːzn/|原因，理由|gn|abstract
record|/ˈrekərd/|记录，唱片|gn|abstract
regret|/rɪˈɡret/|遗憾，后悔|gn|abstract
relation|/rɪˈleɪʃn/|关系，亲戚|gn|abstract
religion|/rɪˈlɪdʒən/|宗教，信仰|gn|abstract
representative|/ˌreprɪˈzentətɪv/|代表，代理人|gn|people
request|/rɪˈkwest/|请求，要求|gn|abstract
respect|/rɪˈspekt/|尊重，方面|gn|abstract
rest|/rest/|休息，其余|gn|abstract
reward|/rɪˈwɔːrd/|奖赏，报酬|gn|abstract
rhythm|/ˈrɪðəm/|节奏，韵律|gn|abstract
rice|/raɪs/|稻米，米饭|gn|food
river|/ˈrɪvər/|河流|gn|nature
road|/roʊd/|道路|gn|abstract
roll|/roʊl/|卷，滚动|gn|abstract
room|/ruːm/|房间，空间|gn|abstract
rub|/rʌb/|摩擦，擦|gn|abstract
rule|/ruːl/|规则，统治|gn|abstract
run|/rʌn/|跑，运营|gn|abstract
salt|/sɒlt/|盐|gn|food
sand|/sænd/|沙|gn|nature
scale|/skeɪl/|规模，比例尺|gn|abstract
science|/ˈsaɪəns/|科学|gn|abstract
sea|/siː/|海|gn|nature
seat|/siːt/|座位|gn|abstract
secretary|/ˈsekrəteri/|秘书|gn|people
selection|/sɪˈlekʃn/|选择|gn|abstract
self|/self/|自我|gn|abstract
sense|/sens/|感觉，意义|gn|abstract
servant|/ˈsɜːrvənt/|仆人|gn|people
sex|/seks/|性别|gn|abstract
shade|/ʃeɪd/|阴凉，阴影|gn|abstract
shake|/ʃeɪk/|摇动，颤抖|gn|abstract
shame|/ʃeɪm/|羞耻，遗憾|gn|abstract
shock|/ʃɒk/|震惊，冲击|gn|abstract
side|/saɪd/|边，方面|gn|abstract
sign|/saɪn/|标志，签名|gn|abstract
silk|/sɪlk/|丝绸|gn|material
silver|/ˈsɪlvər/|银|gn|material
sister|/ˈsɪstər/|姐妹|gn|people
size|/saɪz/|大小，尺寸|gn|abstract
sky|/skaɪ/|天空|gn|nature
sleep|/sliːp/|睡眠|gn|abstract
slip|/slɪp/|滑，溜|gn|abstract
slope|/sloʊp/|斜坡|gn|abstract
smash|/smæʃ/|粉碎，猛撞|gn|abstract
smell|/smel/|气味，闻|gn|abstract
smile|/smaɪl/|微笑|gn|abstract
smoke|/smoʊk/|烟，吸烟|gn|abstract
sneeze|/sniːz/|打喷嚏|gn|abstract
snow|/snoʊ/|雪|gn|nature
soap|/soʊp/|肥皂|gn|abstract
society|/səˈsaɪəti/|社会|gn|abstract
son|/sʌn/|儿子|gn|people
song|/sɒŋ/|歌曲|gn|abstract
sort|/sɔːrt/|种类，排序|gn|abstract
sound|/saʊnd/|声音|gn|abstract
soup|/suːp/|汤|gn|food
space|/speɪs/|空间|gn|abstract
stage|/steɪdʒ/|阶段，舞台|gn|abstract
start|/stɑːrt/|开始|gn|abstract
statement|/ˈsteɪtmənt/|声明，陈述|gn|abstract
steam|/stiːm/|蒸汽|gn|nature
steel|/stiːl/|钢|gn|material
step|/step/|步骤，脚步|gn|abstract
stitch|/stɪtʃ/|针脚，缝|gn|abstract
stone|/stoʊn/|石头|gn|nature
stop|/stɒp/|停止，车站|gn|abstract
story|/ˈstɔːri/|故事|gn|abstract
substance|/ˈsʌbstəns/|物质，实质|gn|abstract
sugar|/ˈʃʊɡər/|糖|gn|food
suggestion|/səˈdʒestʃən/|建议，暗示|gn|abstract
summer|/ˈsʌmər/|夏天|gn|time
support|/səˈpɔːrt/|支持，支撑|gn|abstract
surprise|/sərˈpraɪz/|惊喜，意外|gn|abstract
swim|/swɪm/|游泳|gn|abstract
system|/ˈsɪstəm/|系统，体系|gn|abstract
talk|/tɔːk/|谈话，交谈|gn|abstract
taste|/teɪst/|味道，品味|gn|abstract
tax|/tæks/|税，税款|gn|abstract
teaching|/ˈtiːtʃɪŋ/|教学，教导|gn|abstract
tendency|/ˈtendənsi/|趋势，倾向|gn|abstract
test|/test/|测试，试验|gn|abstract
theory|/ˈθɪəri/|理论，学说|gn|abstract
thing|/θɪŋ/|事物，东西|gn|abstract
thought|/θɔːt/|思想，想法|gn|abstract
thunder|/ˈθʌndər/|雷，雷声|gn|nature
time|/taɪm/|时间，次数|gn|time
tin|/tɪn/|锡，罐头|gn|material
top|/tɒp/|顶部，上面|gn|abstract
touch|/tʌtʃ/|触摸，接触|gn|abstract
trade|/treɪd/|贸易，交易|gn|abstract
transport|/ˈtrænspɔːrt/|运输，交通|gn|abstract
trick|/trɪk/|诡计，技巧|gn|abstract
trouble|/ˈtrʌbl/|麻烦，困难|gn|abstract
turn|/tɜːrn/|转动，转弯|gn|abstract
twist|/twɪst/|扭曲，扭转|gn|abstract
unit|/ˈjuːnɪt/|单位，单元|gn|abstract
use|/juːz/|使用，用途|gn|abstract
value|/ˈvæljuː/|价值，数值|gn|abstract
verse|/vɜːrs/|诗，韵文|gn|abstract
voice|/vɔɪs/|声音，嗓音|gn|abstract
walk|/wɔːk/|步行，散步|gn|abstract
war|/wɔːr/|战争|gn|abstract
wash|/wɒʃ/|洗涤，清洗|gn|abstract
waste|/weɪst/|浪费，废物|gn|abstract
water|/ˈwɔːtər/|水|gn|nature
wave|/weɪv/|波浪，挥手|gn|nature
wax|/wæks/|蜡|gn|material
way|/weɪ/|方式，道路|gn|abstract
weather|/ˈweðər/|天气|gn|nature
week|/wiːk/|周，星期|gn|time
weight|/weɪt/|重量，体重|gn|abstract
wind|/wɪnd/|风|gn|nature
wine|/waɪn/|葡萄酒|gn|food
winter|/ˈwɪntər/|冬天|gn|time
woman|/ˈwʊmən/|女人|gn|people
wood|/wʊd/|木材，树林|gn|material
wool|/wʊl/|羊毛|gn|material
word|/wɜːrd/|词，单词|gn|abstract
work|/wɜːrk/|工作，劳动|gn|abstract
wound|/wuːnd/|伤口，伤害|gn|abstract
writing|/ˈraɪtɪŋ/|写作，文字|gn|abstract
year|/jɪr/|年，年份|gn|time
angle|/ˈæŋɡl/|角，角度|pt|abstract
ant|/ænt/|蚂蚁|pt|animal
apple|/ˈæpl/|苹果|pt|food
arch|/ɑːrtʃ/|拱门，拱形|pt|building
arm|/ɑːrm/|手臂|pt|body
army|/ˈɑːrmi/|军队|pt|people
baby|/ˈbeɪbi/|婴儿|pt|people
bag|/bæɡ/|袋子，包|pt|clothing
ball|/bɔːl/|球|pt|tool
band|/bænd/|带，乐队|pt|tool
basin|/ˈbeɪsn/|盆，盆地|pt|tool
basket|/ˈbæskɪt/|篮子|pt|tool
bath|/bæθ/|浴，洗澡|pt|building
bed|/bed/|床|pt|building
bee|/biː/|蜜蜂|pt|animal
bell|/bel/|铃，钟|pt|tool
berry|/ˈberi/|浆果|pt|food
bird|/bɜːrd/|鸟|pt|animal
blade|/bleɪd/|刀刃，叶片|pt|tool
board|/bɔːrd/|板，董事会|pt|tool
boat|/boʊt/|船|pt|vehicle
bone|/boʊn/|骨头|pt|body
boot|/buːt/|靴子|pt|clothing
bottle|/ˈbɒtl/|瓶子|pt|tool
box|/bɒks/|盒子，箱子|pt|tool
boy|/bɔɪ/|男孩|pt|people
brain|/breɪn/|大脑|pt|body
brake|/breɪk/|刹车|pt|tool
branch|/bræntʃ/|树枝，分支|pt|plant
brick|/brɪk/|砖|pt|building
bridge|/brɪdʒ/|桥|pt|building
brush|/brʌʃ/|刷子|pt|tool
bucket|/ˈbʌkɪt/|桶|pt|tool
bulb|/bʌlb/|灯泡，球茎|pt|tool
cake|/keɪk/|蛋糕|pt|food
camera|/ˈkæmərə/|照相机|pt|tool
cap|/kæp/|帽子|pt|clothing
carriage|/ˈkærɪdʒ/|马车|pt|vehicle
cart|/kɑːrt/|手推车|pt|vehicle
cat|/kæt/|猫|pt|animal
chain|/tʃeɪn/|链子|pt|tool
cheese|/tʃiːz/|奶酪|pt|food
chest|/tʃest/|胸，箱子|pt|body
chin|/tʃɪn/|下巴|pt|body
church|/tʃɜːrtʃ/|教堂|pt|building
circle|/ˈsɜːrkl/|圆，圆圈|pt|abstract
clock|/klɒk/|钟|pt|tool
cloud|/klaʊd/|云|pt|nature
coat|/koʊt/|外套|pt|clothing
collar|/ˈkɒlər/|领子|pt|clothing
comb|/koʊm/|梳子|pt|tool
cord|/kɔːrd/|绳，索|pt|tool
cow|/kaʊ/|牛|pt|animal
cup|/kʌp/|杯子|pt|tool
curtain|/ˈkɜːrtn/|窗帘|pt|building
cushion|/ˈkʊʃn/|垫子|pt|building
dog|/dɒɡ/|狗|pt|animal
door|/dɔːr/|门|pt|building
drain|/dreɪn/|排水沟|pt|building
drawer|/drɔːr/|抽屉|pt|building
dress|/dres/|连衣裙|pt|clothing
drop|/drɒp/|滴，落下|pt|abstract
ear|/ɪr/|耳朵|pt|body
egg|/eɡ/|蛋|pt|food
engine|/ˈendʒɪn/|引擎，发动机|pt|tool
eye|/aɪ/|眼睛|pt|body
face|/feɪs/|脸，面|pt|body
farm|/fɑːrm/|农场|pt|building
feather|/ˈfeðər/|羽毛|pt|animal
finger|/ˈfɪŋɡər/|手指|pt|body
fish|/fɪʃ/|鱼|pt|animal
flag|/flæɡ/|旗帜|pt|abstract
floor|/flɔːr/|地板，楼层|pt|building
fly|/flaɪ/|苍蝇|pt|animal
foot|/fʊt/|脚|pt|body
fork|/fɔːrk/|叉|pt|tool
fowl|/faʊl/|家禽|pt|animal
frame|/freɪm/|框架|pt|tool
garden|/ˈɡɑːrdn/|花园|pt|building
girl|/ɡɜːrl/|女孩|pt|people
glove|/ɡlʌv/|手套|pt|clothing
goat|/ɡoʊt/|山羊|pt|animal
gun|/ɡʌn/|枪|pt|tool
hair|/her/|头发|pt|body
hammer|/ˈhæmər/|锤子|pt|tool
hand|/hænd/|手|pt|body
hat|/hæt/|帽子|pt|clothing
head|/hed/|头|pt|body
heart|/hɑːrt/|心，心脏|pt|body
hook|/hʊk/|钩子|pt|tool
horn|/hɔːrn/|角，号角|pt|animal
horse|/hɔːrs/|马|pt|animal
hospital|/ˈhɒspɪtl/|医院|pt|building
house|/haʊs/|房子|pt|building
island|/ˈaɪlənd/|岛|pt|nature
jewel|/ˈdʒuːəl/|宝石|pt|tool
kettle|/ˈketl/|水壶|pt|tool
key|/kiː/|钥匙|pt|tool
knee|/niː/|膝盖|pt|body
knife|/naɪf/|刀|pt|tool
knot|/nɒt/|结|pt|abstract
leaf|/liːf/|叶子|pt|plant
leg|/leɡ/|腿|pt|body
library|/ˈlaɪbrəri/|图书馆|pt|building
line|/laɪn/|线，排|pt|abstract
lip|/lɪp/|嘴唇|pt|body
lock|/lɒk/|锁|pt|tool
map|/mæp/|地图|pt|tool
match|/mætʃ/|火柴，比赛|pt|tool
mirror|/ˈmɪrər/|镜子|pt|tool
monkey|/ˈmʌŋki/|猴子|pt|animal
moon|/muːn/|月亮|pt|nature
mouth|/maʊθ/|嘴|pt|body
muscle|/ˈmʌsl/|肌肉|pt|body
nail|/neɪl/|钉子，指甲|pt|body
neck|/nek/|脖子|pt|body
needle|/ˈniːdl/|针|pt|tool
nerve|/nɜːrv/|神经|pt|body
net|/net/|网|pt|tool
nose|/noʊz/|鼻子|pt|body
nut|/nʌt/|坚果|pt|food
office|/ˈɒfɪs/|办公室|pt|building
orange|/ˈɒrɪndʒ/|橙子|pt|food
oven|/ˈʌvn/|烤箱|pt|building
parcel|/ˈpɑːrsl/|包裹|pt|tool
pen|/pen/|钢笔|pt|tool
pencil|/ˈpensl/|铅笔|pt|tool
picture|/ˈpɪktʃər/|图片，画|pt|abstract
pig|/pɪɡ/|猪|pt|animal
pin|/pɪn/|针，别针|pt|tool
pipe|/paɪp/|管子|pt|tool
plane|/pleɪn/|飞机|pt|vehicle
plate|/pleɪt/|盘子|pt|tool
pocket|/ˈpɒkɪt/|口袋|pt|clothing
pot|/pɒt/|锅|pt|tool
potato|/pəˈteɪtoʊ/|土豆|pt|food
prison|/ˈprɪzn/|监狱|pt|building
pump|/pʌmp/|泵|pt|tool
rail|/reɪl/|铁路，栏杆|pt|tool
rat|/ræt/|老鼠|pt|animal
roof|/ruːf/|屋顶|pt|building
root|/ruːt/|根|pt|plant
sail|/seɪl/|帆|pt|vehicle
school|/skuːl/|学校|pt|building
scissors|/ˈsɪzərz/|剪刀|pt|tool
seed|/siːd/|种子|pt|plant
sheep|/ʃiːp/|羊|pt|animal
ship|/ʃɪp/|船|pt|vehicle
shirt|/ʃɜːrt/|衬衫|pt|clothing
shoe|/ʃuː/|鞋|pt|clothing
shop|/ʃɒp/|商店|pt|building
shoulder|/ˈʃoʊldər/|肩膀|pt|body
sponge|/spʌndʒ/|海绵|pt|tool
spoon|/spuːn/|勺子|pt|tool
stamp|/stæmp/|邮票，印章|pt|tool
stem|/stem/|茎，干|pt|plant
stick|/stɪk/|棍，棒|pt|tool
stocking|/ˈstɒkɪŋ/|长袜|pt|clothing
stomach|/ˈstʌmək/|胃，肚子|pt|body
street|/striːt/|街道|pt|building
sun|/sʌn/|太阳|pt|nature
table|/ˈteɪbl/|桌子|pt|tool
tail|/teɪl/|尾巴|pt|animal
tank|/tæŋk/|水箱，坦克|pt|tool
tap|/tæp/|水龙头|pt|tool
thumb|/θʌm/|拇指|pt|body
ticket|/ˈtɪkɪt/|票|pt|tool
tongue|/tʌŋ/|舌头|pt|body
tooth|/tuːθ/|牙齿|pt|body
town|/taʊn/|城镇|pt|building
track|/træk/|轨道，小路|pt|tool
train|/treɪn/|火车|pt|vehicle
tray|/treɪ/|托盘|pt|tool
tree|/triː/|树|pt|plant
trousers|/ˈtraʊzərz/|裤子|pt|clothing
umbrella|/ʌmˈbrelə/|雨伞|pt|tool
wall|/wɔːl/|墙|pt|building
watch|/wɒtʃ/|手表|pt|tool
wheel|/wiːl/|轮子|pt|tool
whip|/wɪp/|鞭子|pt|tool
window|/ˈwɪndoʊ/|窗户|pt|building
wing|/wɪŋ/|翅膀|pt|animal
wire|/waɪər/|线，金属丝|pt|tool
worm|/wɜːrm/|虫子|pt|animal
zebra|/ˈziːbrə/|斑马|pt|animal
able|/ˈeɪbl/|有能力的|qg|adj
acid|/ˈæsɪd/|酸的，酸性的|qg|adj
angry|/ˈæŋɡri/|愤怒的|qg|adj
automatic|/ˌɔːtəˈmætɪk/|自动的|qg|adj
beautiful|/ˈbjuːtɪfl/|美丽的|qg|adj
black|/blæk/|黑色的|qg|adj
boiling|/ˈbɔɪlɪŋ/|沸腾的|qg|adj
bright|/braɪt/|明亮的，聪明的|qg|adj
broken|/ˈbroʊkən/|破碎的|qg|adj
brown|/braʊn/|棕色的|qg|adj
cheap|/tʃiːp/|便宜的|qg|adj
chemical|/ˈkemɪkl/|化学的|qg|adj
chief|/tʃiːf/|主要的，首席的|qg|adj
clean|/kliːn/|干净的|qg|adj
clear|/klɪr/|清晰的|qg|adj
common|/ˈkɒmən/|常见的，共同的|qg|adj
complex|/ˈkɒmpleks/|复杂的|qg|adj
conscious|/ˈkɒnʃəs/|有意识的|qg|adj
cut|/kʌt/|切开的|qg|adj
deep|/diːp/|深的|qg|adj
dependent|/dɪˈpendənt/|依赖的|qg|adj
early|/ˈɜːrli/|早的|qg|adj
elastic|/ɪˈlæstɪk/|有弹性的|qg|adj
electric|/ɪˈlektrɪk/|电的|qg|adj
equal|/ˈiːkwəl/|平等的|qg|adj
fat|/fæt/|胖的|qg|adj
first|/fɜːrst/|第一的|qg|adj
fixed|/fɪkst/|固定的|qg|adj
flat|/flæt/|平的|qg|adj
free|/friː/|自由的，免费的|qg|adj
frequent|/ˈfriːkwənt/|频繁的|qg|adj
full|/fʊl/|满的|qg|adj
general|/ˈdʒenərəl/|一般的，总的|qg|adj
good|/ɡʊd/|好的|qg|adj
great|/ɡreɪt/|伟大的|qg|adj
grey|/ɡreɪ/|灰色的|qg|adj
hanging|/ˈhæŋɪŋ/|悬挂的|qg|adj
happy|/ˈhæpi/|快乐的|qg|adj
hard|/hɑːrd/|硬的，困难的|qg|adj
healthy|/ˈhelθi/|健康的|qg|adj
high|/haɪ/|高的|qg|adj
hollow|/ˈhɒloʊ/|空的，中空的|qg|adj
important|/ɪmˈpɔːrtənt/|重要的|qg|adj
kind|/kaɪnd/|善良的|qg|adj
like|/laɪk/|相似的|qg|adj
living|/ˈlɪvɪŋ/|活的|qg|adj
long|/lɒŋ/|长的|qg|adj
male|/meɪl/|男性的|qg|adj
married|/ˈmærid/|已婚的|qg|adj
material|/məˈtɪriəl/|物质的|qg|adj
medical|/ˈmedɪkl/|医学的|qg|adj
military|/ˈmɪləteri/|军事的|qg|adj
natural|/ˈnætʃərəl/|自然的|qg|adj
necessary|/ˈnesəseri/|必要的|qg|adj
new|/njuː/|新的|qg|adj
normal|/ˈnɔːrml/|正常的|qg|adj
open|/ˈoʊpən/|开放的|qg|adj
parallel|/ˈpærəlel/|平行的|qg|adj
past|/pæst/|过去的|qg|adj
physical|/ˈfɪzɪkl/|身体的，物理的|qg|adj
plain|/pleɪn/|朴素的，平坦的|qg|adj
poor|/pʊr/|穷的，可怜的|qg|adj
possible|/ˈpɒsəbl/|可能的|qg|adj
present|/ˈpreznt/|现在的|qg|adj
private|/ˈpraɪvət/|私人的|qg|adj
probable|/ˈprɒbəbl/|很可能的|qg|adj
quick|/kwɪk/|快的|qg|adj
quiet|/ˈkwaɪət/|安静的|qg|adj
ready|/ˈredi/|准备好的|qg|adj
red|/red/|红色的|qg|adj
regular|/ˈreɡjələr/|规律的|qg|adj
responsible|/rɪˈspɒnsəbl/|负责的|qg|adj
right|/raɪt/|对的，右边的|qg|adj
rough|/rʌf/|粗糙的|qg|adj
round|/raʊnd/|圆的|qg|adj
same|/seɪm/|相同的|qg|adj
second|/ˈsekənd/|第二的|qg|adj
separate|/ˈsepəreɪt/|分开的|qg|adj
serious|/ˈsɪriəs/|严肃的|qg|adj
sharp|/ʃɑːrp/|锋利的|qg|adj
smooth|/smuːð/|光滑的|qg|adj
sticky|/ˈstɪki/|粘的|qg|adj
stiff|/stɪf/|僵硬的|qg|adj
straight|/streɪt/|直的|qg|adj
strong|/strɒŋ/|强壮的|qg|adj
sudden|/ˈsʌdn/|突然的|qg|adj
sweet|/swiːt/|甜的|qg|adj
tall|/tɔːl/|高的|qg|adj
thick|/θɪk/|厚的|qg|adj
tight|/taɪt/|紧的|qg|adj
tired|/taɪərd/|疲倦的|qg|adj
true|/truː/|真实的|qg|adj
violent|/ˈvaɪələnt/|暴力的|qg|adj
waiting|/ˈweɪtɪŋ/|等待的|qg|adj
warm|/wɔːrm/|温暖的|qg|adj
wet|/wet/|湿的|qg|adj
wide|/waɪd/|宽的|qg|adj
wise|/waɪz/|明智的|qg|adj
yellow|/ˈjeloʊ/|黄色的|qg|adj
young|/jʌŋ/|年轻的|qg|adj
wrong|/rɒŋ/|错误的|qg|adj
awake|/əˈweɪk/|醒着的|qo|adj
bad|/bæd/|坏的|qo|adj
bent|/bent/|弯的|qo|adj
bitter|/ˈbɪtər/|苦的|qo|adj
dark|/dɑːrk/|黑暗的|qo|adj
dead|/ded/|死的|qo|adj
different|/ˈdɪfrənt/|不同的|qo|adj
dirty|/ˈdɜːrti/|脏的|qo|adj
dry|/draɪ/|干的|qo|adj
false|/fɔːls/|假的|qo|adj
feeble|/ˈfiːbl/|虚弱的|qo|adj
female|/ˈfiːmeɪl/|女性的|qo|adj
foreign|/ˈfɒrən/|外国的|qo|adj
future|/ˈfjuːtʃər/|未来的|qo|adj
green|/ɡriːn/|绿色的|qo|adj
ill|/ɪl/|生病的|qo|adj
last|/læst/|最后的|qo|adj
late|/leɪt/|迟的|qo|adj
left|/left/|左边的|qo|adj
low|/loʊ/|低的|qo|adj
mixed|/mɪkst/|混合的|qo|adj
narrow|/ˈnæroʊ/|窄的|qo|adj
opposite|/ˈɒpəzɪt/|相反的|qo|adj
poor|/pʊr/|贫穷的|qo|adj
present|/ˈpreznt/|在场的|qo|adj
private|/ˈpraɪvət/|私密的|qo|adj
public|/ˈpʌblɪk/|公共的|qo|adj
rough|/rʌf/|粗略的|qo|adj
sad|/sæd/|悲伤的|qo|adj
short|/ʃɔːrt/|短的|qo|adj
shut|/ʃʌt/|关闭的|qo|adj
simple|/ˈsɪmpl/|简单的|qo|adj
slow|/sloʊ/|慢的|qo|adj
small|/smɔːl/|小的|qo|adj
soft|/sɒft/|软的|qo|adj
solid|/ˈsɒlɪd/|固体的|qo|adj
special|/ˈspeʃl/|特别的|qo|adj
still|/stɪl/|静止的|qo|adj
straight|/streɪt/|直接的|qo|adj
strange|/streɪndʒ/|奇怪的|qo|adj
thin|/θɪn/|薄的|qo|adj
tight|/taɪt/|紧密的|qo|adj
ugly|/ˈʌɡli/|丑的|qo|adj
unconscious|/ʌnˈkɒnʃəs/|无意识的|qo|adj
unequal|/ʌnˈiːkwəl/|不平等的|qo|adj
unused|/ʌnˈjuːzd/|未使用的|qo|adj
weak|/wiːk/|弱的|qo|adj
wet|/wet/|潮湿的|qo|adj
white|/waɪt/|白色的|qo|adj
wide|/waɪd/|宽阔的|qo|adj
young|/jʌŋ/|年幼的|qo|adj
also|/ˈɔːlsoʊ/|也，而且|op|adv
always|/ˈɔːlweɪz/|总是，一直|op|adv
never|/ˈnevər/|从不|op|adv
often|/ˈɒfn/|经常|op|adv
soon|/suːn/|很快，不久|op|adv
too|/tuː/|也，太|op|adv
yet|/jet/|然而，还|op|adv
already|/ɔːlˈredi/|已经|op|adv
just|/dʒʌst/|刚刚，只是|op|adv
rather|/ˈræðər/|相当，宁愿|op|adv
perhaps|/pərˈhæps/|也许，可能|op|adv
it|/ɪt/|它|op|pron
me|/miː/|我（宾格）|op|pron
him|/hɪm/|他（宾格）|op|pron
her|/hɜːr/|她，她的|op|pron
them|/ðem/|他们（宾格）|op|pron
us|/ʌs/|我们（宾格）|op|pron`;
